workspace:
  base: /go

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  latest:
    image: plugins/docker
    repo: vallard/drone-kube
    tags: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: Kube
  desc: Update Deployments on kubernetes
  type: deploy
  image: vallard/drone-kube
